spring.application.name=Sprachraume
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

#spring.jpa.properties.hibernate.auto_quote_keyword=true
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
springdoc.swagger-ui.use-root-path=true
server.forward-headers-strategy=framework
server.port=${PORT:8080}
server.servlet.context-path=/api
key.access=HE4CyDvzayUFP1iVLNCV7bixOtmnJm9ICA//heBc7+U=
key.refresh=XF6VUpZEtQzPkUsYjDVw1yGgA6T6jNsBnkPt40xnLzU=

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=organicvladn09@gmail.com
#spring.mail.password=${GMAIL_APP_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true



# Daily.co settings
daily.api.url=https://api.daily.co/v1
daily.api.key=${YOUR_DAILY_API_KEY}





#spring.security.oauth2.client.registration.google.client-id=74073758675-606h8lg156miorpg76kj6e0qbdmltfuj.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/oauth2/callback/google
#spring.security.oauth2.client.registration.google.scope=email,profile