spring.application.name=Sprachraume

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${MY_SQL_NAME}
spring.datasource.password=${MY_SQL_PASSWORD}
#spring.jpa.properties.hibernate.auto_quote_keyword=true
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
#logging.level.org.springframework.security=DEBUG




server.servlet.context-path=/api






key.access=HE4CyDvzayUFP1iVLNCV7bixOtmnJm9ICA//heBc7+U=
key.refresh=XF6VUpZEtQzPkUsYjDVw1yGgA6T6jNsBnkPt40xnLzU=



# Daily.co settings
daily.api.url=https://api.daily.co/v1
daily.api.key=${YOUR_DAILY_API_KEY}





#spring.security.oauth2.client.registration.google.client-id=74073758675-606h8lg156miorpg76kj6e0qbdmltfuj.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/oauth2/callback/google
#spring.security.oauth2.client.registration.google.scope=email,profile